name: accessibility_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  flutter_tts: ^4.0.2
  uuid: ^4.3.3
  flutter_signature_pad: ^3.0.1
  http: ^1.2.1
  firebase_auth: ^4.19.4
  firebase_database: ^10.5.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Dongle
      fonts:
        - asset: assets/fonts/DongleBold.ttf
          weight: 700
        - asset: assets/fonts/DongleLight.ttf
          weight: 300
